# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MIT 中国发展行动
email: mit-cdi@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  China Development Initiative (CDI) is an MIT student organization founded by MIT undergraduates aiming to:
  1. provide MIT students with more opportunities to learn about China's development, often through sustainable programs like SLP
  2. establish connections and bridge the cultural gap between MIT students and students in China
  3. engage in meaningful exchange with students and thought leaders in China to promote mutual understanding, particularly via forums on leadership, citizenship, and international consciousness
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cdi.mit.edu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
